# Generated by Django 4.2.13 on 2024-05-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
